apiVersion: apps/v1
kind: Deployment
metadata:
  name: voicesphere-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: voicesphere-backend
  template:
    metadata:
      labels:
        app: voicesphere-backend
    spec:
      containers:
      - name: voicesphere-backend
        image: voicesphere-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOSTS
          value: "scylla-0.scylla-service"
        - name: DB_PORT
          value: "9042"
        - name: DB_KEYSPACE
          value: "voicesphere"
        - name: RUST_LOG
          value: "info"
        volumeMounts:
        - name: source-code
          mountPath: /usr/src/app
      volumes:
      - name: source-code
        hostPath:
          path: /run/desktop/mnt/host/f/Project/wakie-app/backend/VoiceSphereBackend
          type: Directory
