apiVersion: v1
kind: Service
metadata:
  name: voicesphere-backend-service
spec:
  type: LoadBalancer
  selector:
    app: voicesphere-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
